vagrantfile:
    target: local
    vm:
        provider:
            local:
                box: bento/ubuntu-16.04
                box_url: 'false'
                box_version: '0'
                chosen_virtualizer: virtualbox
                virtualizers:
                    virtualbox:
                        modifyvm:
                            natdnshostresolver1: false
                        showgui: 0
                    vmware:
                        numvcpus: 1
                    parallels:
                        linked_clone: 0
                        check_guest_tools: 0
                        update_guest_tools: 0
                machines:
                    magento:
                        id: magento2demo
                        hostname: magento2.local
                        network:
                            private_network: 192.168.31.66
                            forwarded_port:
                                port1:
                                    host: '8133'
                                    guest: '22'
                        memory: '6096'
                        cpus: '4'
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                module_path:
                    - puphpet/puppet/modules
                    - puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
        synced_folder:
            str_qwgnu9g5lt:
                owner: www-data
                group: www-data
                source: ./public_html
                target: /home/vagrant/www
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
            str_aqdtmslipi:
                owner: www-data
                group: www-data
                source: ./databases
                target: /var/databases
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
            str_kgqoqjvrc9:
                owner: www-data
                group: www-data
                source: ./configs
                target: /var/configs
                sync_type: nfs
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                    mount_options:
                        dir_mode: '0775'
                        file_mode: '0664'
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
        usable_port_range:
            start: 10200
            stop: 10500
        post_up_message: ''
    ssh:
        host: 'false'
        port: 'false'
        private_key_path: 'false'
        username: vagrant
        guest_port: 'false'
        keep_alive: '1'
        forward_agent: 'false'
        forward_x11: 'false'
        shell: 'bash -l'
        insert_key: 'false'
    vagrant:
        host: detect
    proxy:
        http: ''
        https: ''
        ftp: ''
        no_proxy: ''
server:
    install: '1'
    packages:
        - bash-completion
        - htop
        - vim
        - nano
users_groups:
    install: '1'
    groups:
        - magento
    users:
        - magento
locale:
    install: '1'
    settings:
        default_locale: en_GB.UTF-8
        locales:
            - en_GB.UTF-8
            - en_US.UTF-8
        timezone: UTC
firewall:
    install: '1'
    rules: {  }
resolv:
    install: '1'
    nameservers:
        - 8.8.8.8
        - 8.8.4.4
    domainname: ''
    searchpath: {  }
cron:
    install: '0'
#    jobs:
#        cronjob1:
#            name: magento-cron1
#            user: www-user
#            command: '/usr/bin/php7.2 /home/vagrant/www/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /home/vagrant/www/var/log/magento.cron.log'
#            minute: '*'
#            hour: '*'
#            weekday: '*'
#            month: '*'
#            monthday: ''
#        cronjob2:
#            name: magento-cron2
#            user: www-user
#            command: '/usr/bin/php7.2 /home/vagrant/www/update/cron.php >> /home/vagrant/www/var/log/update.cron.log'
#            minute: '*'
#            hour: '*'
#            weekday: '*'
#            month: '*'
#            monthday: ''
#        cronjob3:
#            name: magento-cron3
#            user: www-user
#            command: '/usr/bin/php7.2 /home/vagrant/www/bin/magento setup:cron:run >> /home/vagrant/www/var/log/setup.cron.log'
#            minute: '*'
#            hour: '*'
#            weekday: '*'
#            month: '*'
#            monthday: ''
nginx:
    install: '1'
    settings:
        version: present
        default_vhost: 1
        proxy_buffers: '4 256k'
        proxy_buffer_size: 128k
        proxy_connect_timeout: 600s
        proxy_send_timeout: 600s
        proxy_read_timeout: 600s
        names_hash_bucket_size: 128
    upstreams: {  }
    vhosts:
        magento:
            server_name: magento2.local
            server_aliases:
                - www.magento2.local
            www_root: /home/vagrant/www
            listen_port: '80'
            client_max_body_size: 25m
            ssl: '0'
    proxies: {  }
apache:
    install: '0'
    settings:
        version: 2.4
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        vhost1:
            servername: awesome.test
            serveraliases:
                - www.awesome.test
            docroot: /var/www/awesome
            port: '80'
            setenvif:
                - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
            ssl: '0'
            ssl_cert: LETSENCRYPT
            ssl_key: LETSENCRYPT
            ssl_chain: LETSENCRYPT
            ssl_certs_dir: LETSENCRYPT
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                php_html:
                    provider: directory
                    path: /var/www/awesome
                    directoryindex: 'index.php index.html'
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                php_php:
                    provider: filesmatch
                    path: \.php$
                    sethandler: 'proxy:fcgi://127.0.0.1:9000'
letsencrypt:
    install: '0'
    settings:
        email: ''
        webserver_service: ''
    domains: {  }
php:
    install: '1'
    settings:
        version: '7.2'
    modules:
        php:
            - cli
            - intl
            - xml
            - mbstring
            - gd
            - zip
            - simplexml
            - soap
            - curl
            - xsl
            - pdo
            - iconv
            - mysqlnd
            - bcmath
            - opcache
            - json
            - imagick
        pear: {  }
        pecl: {  }
    ini:
        display_errors: 'On'
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        max_input_vars: '100000'
        max_input_time: '-1'
        opcache.enable: '1'
        memory_limit: 2G
        asp_tags: 'Off'
        opcache.save_comments: '1'
        upload_max_filesize: 512M
        max_file_uploads: 200
        post_max_size: 512M
        sendmail_path: '/usr/local/bin/mhsendmail --smtp-addr=mailhog.grvytrn.co.uk:1025'
        max_execution_time: 18000
        default_socket_timeout: 600
        gc_maxlifetime: 172800
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        str_mux0owajin:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '1'
    settings:
        xdebug.remote_enable: true
        xdebug.remote_connect_back: on
        xdebug.remote_port: 9000
        xdebug.idekey: PHPSTORM
        xdebug.profiler_enable: Off
        xdebug.profiler_enable_trigger: On
        xdebug.profiler_output_dir: "/home/vagrant/www/var/xdebug"
        xdebug.profiler_output_name: "cachegrind.out.%u"
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
wpcli:
    install: '1'
drush:
    install: '0'
    version: 8.0.5
#ruby:
#    install: '1'
#    versions:
#        str_7v9bln3uat:
#            default: '1'
#            bundler: '1'
#            version: '2.4'
#            gems:
#                - deep_merge@1.2.1
#                - activesupport@5.1.4
#                - vine@0.4
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    settings:
        version: '6'
    npm_packages: {  }
mariadb:
    install: '0'
    settings:
        version: '10.1'
        root_password: '123'
        override_options: {  }
    users:
        user1:
            name: dbuser
            password: '123'
    databases:
        database1:
            name: dbname
            collate: utf8_general_ci
            sql: ''
    grants:
        grant1:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: root
        override_options: {  }
    users:
        str_zskow2m53w:
            name: magento
            password: mage123123
    databases:
        str_gybsbk5cen:
            name: magento
            collate: utf8_general_ci
            sql: /var/databases/local/magento-local.sql
    grants:
        str_0rbro5xhrh:
            user: magento
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '0'
    settings:
        global:
            encoding: UTF8
            version: '9.6'
        server:
            postgres_password: '123'
    databases:
        database1:
            dbname: dbname
            owner: dbuser
    users:
        user1:
            username: dbuser
            password: '123'
            superuser: '1'
    grants:
        grant1:
            role: dbuser
            db: dbname
            privilege:
                - ALL
mongodb:
    install: '0'
    settings:
        bind_ip: 127.0.0.1
        port: '27017'
    globals:
        version: 3.6.2
    databases:
        database1:
            name: dbname
            user: dbuser
            password: '123'
redis:
    install: '1'
    settings:
        port: '6379'
sqlite:
    install: '0'
    databases:
        database1:
            name: dbname
            owner: www-data
            group: www-data
            sql_file: ''
mailhog:
    install: '1'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '8025'
        path: /usr/local/bin/mailhog
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '11300'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users:
        user1:
            admin: '1'
            name: admin
            password: '123'
            tags:
                - admin
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '1'
    settings:
        version: 6.1.2
        java_install: true
    instances:
        instance1:
            name: es-01
            jvm_options:
                - '-Xms2G'
                - '-Xmx2G'

